version: "2.1"

networks:
  telemetry_service:
    external: true
    name: my_network

services:
  #my services
  testservice:
    container_name: testservice
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    mem_limit: "1g"
    mem_reservation: "512m"
    entrypoint: "java 
      -Xmx10g
      -javaagent:/home/docker/opentelemetry-javaagent.jar
      -Dotel.service.name=test_service
      -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
      -Dotel.traces.exporter=otlp
      -Dotel.metrics.exporter=otlp
      -Dservice1.url=http://testservice1:8081/
      -Dspring.kafka.consumer.bootstrap-servers=broker:29092 
      -Dspring.kafka.producer.bootstrap-servers=broker:29092
      -jar TestService-0.0.1-SNAPSHOT.jar"
    networks:
      - telemetry_service
    volumes:
      - ../../TestService/target/TestService-0.0.1-SNAPSHOT.jar:/home/docker/TestService-0.0.1-SNAPSHOT.jar
      - ../opentelemetry-javaagent.jar:/home/docker/opentelemetry-javaagent.jar
